production:
  deploy_host: "127.0.0.1"
  username: "foo"
  remote_path: "/webapps/tb_acme"
  acme_endpoint: "https://acme-v02.api.letsencrypt.org/directory"
  public_path: "/webapps/tb_acme/public"
  private_path: "/webapps/tb_acme/private"
  owner_email: "mailto:help@teachbase.ru"
  front_domain: "go.teachbase.ru"
  repository: https://github.com/teachbase/tb-acme
  raven_dsn: "https://example.com"
  cloud_redis: true
  redis_master:
    url: "redis://:JktEDAGpGZ8KB3JS4rD@84.201.130.180:6379/0"
