production:
  deploy_host: '127.0.0.1'
  username: 'foo'
  remote_path: '/webapps/tb-acme'
  acme_endpoint: 'https://acme-v02.api.letsencrypt.org/directory'
  public_path: '/webapps/teachbase/teachbase2/public'
  private_path: '/webapps/teachbase/teachbase2/private'
  owner_email: 'mailto:help@teachbase.ru'
  front_domain: 'go.teachbase.ru'
  raven_dsn: <%= ENV['RAVEN_DSN'] %>
  repository: https://github.com/teachbase/tb-acme
